/*
 * Copyright 2026 GWT Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package java.util.random;

public interface RandomGenerator {

    /**
     * Returns the next pseudo-random, uniformly distributed {@code boolean} value
     * generated by this generator.
     *
     * @return a pseudo-random, uniformly distributed boolean value.
     */
    boolean nextBoolean();

    /**
     * Generates a uniformly distributed 32-bit {@code int} value from the random
     * number sequence.
     *
     * @return a uniformly distributed {@code int} value.
     * @see java.lang.Integer#MAX_VALUE
     * @see java.lang.Integer#MIN_VALUE
     * @see #nextLong
     */
    int nextInt();

    /**
     * Returns a new pseudo-random {@code int} value which is uniformly
     * distributed between 0 (inclusively) and the value of {@code n}
     * (exclusively).
     *
     * @param n the exclusive upper border of the range [0 - n).
     * @return a random {@code int}.
     */
    int nextInt(int n);

    /**
     * Generates a uniformly distributed 64-bit integer value from the random
     * number sequence.
     *
     * @return 64-bit random integer.
     * @see java.lang.Integer#MAX_VALUE
     * @see java.lang.Integer#MIN_VALUE
     * @see #nextInt()
     * @see #nextInt(int)
     */
    long nextLong();

    /**
     * Generates a normally distributed random {@code float} number between 0.0
     * inclusively and 1.0 exclusively.
     *
     * @return float a random {@code float} number between [0.0 and 1.0)
     * @see #nextDouble
     */
    float nextFloat();

    /**
     * Generates a normally distributed random {@code double} number between 0.0
     * inclusively and 1.0 exclusively.
     *
     * @return a random {@code double} in the range [0.0 - 1.0)
     * @see #nextFloat
     */
    double nextDouble();

    /**
     * Pseudo-randomly generates (approximately) a normally distributed {@code
     * double} value with mean 0.0 and a standard deviation value of {@code 1.0}
     * using the <i>polar method<i> of G. E. P. Box, M. E. Muller, and G.
     * Marsaglia, as described by Donald E. Knuth in <i>The Art of Computer
     * Programming, Volume 2: Seminumerical Algorithms</i>, section 3.4.1,
     * subsection C, algorithm P.
     *
     * @return a random {@code double}
     * @see #nextDouble
     */
    double nextGaussian();

    /**
     * Modifies the {@code byte} array by a random sequence of {@code byte}s
     * generated by this random number generator.
     *
     * @param buf non-null array to contain the new random {@code byte}s.
     */
    void nextBytes(byte[] buf);
}