package com.google.gwt.core.client.interop;

import com.google.gwt.core.client.js.JsFunction;
import com.google.gwt.core.client.js.JsType;

/**
 * TODO: Insert description here. (generated by leafwang)
 */
@JsFunction
public interface MyJsFunctionIdentityInterface {
  Object identity();
}
